### ISSUE TITLE
README.md says to point Slack's slash command at /handle instead of /switch

### ISSUE THREAD

**Issue by arkhaix** [psjay/ph-slack#1]
After following the original instructions, I wound up seeing an "Unsupported story" exception whenever I did a /slashcommand enable in Slack.  From what little I understand from digging around in the code, it looks like Slack should be pointed at /switch instead of /handle.  That seems to have worked for me, anyway.

**Comment by psjay** [comment]
Thank you for reporting this. It has been fixed now. :)
